// GOODS
export const GOODS_FETCH_DATA_REJECT = 'GOODS_FETCH_DATA_REJECT';
export const GOODS_FETCH_DATA_REQUEST = 'GOODS_FETCH_DATA_REQUEST';
export const GOODS_FETCH_DATA_SUCCESS = 'GOODS_FETCH_DATA_SUCCESS';
export const GOODS_LOAD_MORE = 'GOODS_LOAD_MORE';
export const GOODS_RESET_LIMIT = 'GOODS_RESET_LIMIT';
export const FIND_GOODS = 'FIND_GOODS';
export const GOODS_SET_VISIBILITY_FILTER = 'GOODS_SET_VISIBILITY_FILTER';
export const SYNC_QUANTITY = 'SYNC_QUANTITY';
export const CHANGE_INPUT = 'CHANGE_INPUT';

//ADMIN
export const OPERATION_DATA_REJECT = 'OPERATION_DATA_REJECT';
export const OPERATION_DATA_REQUEST = 'OPERATION_DATA_REQUEST';
export const OPERATION_DELETE_DATA_SUCCESS = 'OPERATION_DELETE_DATA_SUCCESS';
export const OPERATION_CHANGE_DATA_SUCCESS = 'OPERATION_CHANGE_DATA_SUCCESS';
export const OPERATION_СREATE_DATA_SUCCESS = 'OPERATION_СREATE_DATA_SUCCESS';



// NavBar menu
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';

//Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';