// GOODS
export const GOODS_FETCH_DATA_REJECT = 'GOODS_FETCH_DATA_REJECT';
export const GOODS_FETCH_DATA_REQUEST = 'GOODS_FETCH_DATA_REQUEST';
export const GOODS_FETCH_DATA_SUCCESS = 'GOODS_FETCH_DATA_SUCCESS';
export const GOODS_LOAD_MORE = 'GOODS_LOAD_MORE';
export const GOODS_RESET_LIMIT = 'GOODS_RESET_LIMIT';
export const FIND_GOODS = 'FIND_GOODS';
export const GOODS_SET_VISIBILITY_FILTER = 'GOODS_SET_VISIBILITY_FILTER';
export const SYNC_QUANTITY = 'SYNC_QUANTITY';


//USERS
export const USERS_FETCH_DATA_REJECT = 'USERS_FETCH_DATA_REJECT';
export const USERS_FETCH_DATA_REQUEST = 'USERS_FETCH_DATA_REQUEST';
export const USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS';
export const FIND_USERS = 'FIND_USERS';
export const USERS_SET_VISIBILITY_FILTER = 'USERS_SET_VISIBILITY_FILTER';
export const USER_OPERATION_DATA_REJECT = 'USER_OPERATION_DATA_REJECT';
export const USER_OPERATION_DATA_REQUEST = 'USER_OPERATION_DATA_REQUEST';
export const USER_OPERATION_DELETE_DATA_SUCCESS = 'USER_OPERATION_DELETE_DATA_SUCCESS';
export const USER_OPERATION_CHANGE_DATA_SUCCESS = 'USER_OPERATION_CHANGE_DATA_SUCCESS';
export const USER_OPERATION_СREATE_DATA_SUCCESS = 'USER_OPERATION_СREATE_DATA_SUCCESS';
export const USER_VISIBLE_OPERATION_FORM = 'USER_VISIBLE_OPERATION_FORM';
export const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE';

//ADMIN
export const PRODUCT_OPERATION_DATA_REJECT = 'PRODUCT_OPERATION_DATA_REJECT';
export const PRODUCT_OPERATION_DATA_REQUEST = 'PRODUCT_OPERATION_DATA_REQUEST';
export const PRODUCT_OPERATION_DELETE_DATA_SUCCESS = 'PRODUCT_OPERATION_DELETE_DATA_SUCCESS';
export const PRODUCT_OPERATION_CHANGE_DATA_SUCCESS = 'PRODUCT_OPERATION_CHANGE_DATA_SUCCESS';
export const PRODUCT_OPERATION_СREATE_DATA_SUCCESS = 'PRODUCT_OPERATION_СREATE_DATA_SUCCESS';
export const PRODUCT_VISIBLE_OPERATION_FORM = 'VISIBLE_OPERATION_FORM';
export const PRODUCT_INPUT_CHANGE = 'PRODUCT_INPUT_CHANGE';

// NavBar menu
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';

//Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';