// GOODS
export const GOODS_FETCH_DATA_REJECT = 'GOODS_FETCH_DATA_REJECT';
export const GOODS_FETCH_DATA_REQUEST = 'GOODS_FETCH_DATA_REQUEST';
export const GOODS_FETCH_DATA_SUCCESS = 'GOODS_FETCH_DATA_SUCCESS';
export const GOODS_LOAD_MORE = 'GOODS_LOAD_MORE';
export const GOODS_RESET_LIMIT = 'GOODS_RESET_LIMIT';
export const FIND_GOODS = 'FIND_GOODS';


// NavBar menu
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';
//ADMIN
export const CREATE_GOOD_SUCCESS = 'CREATE_GOOD_SUCCESS';

